- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
    
- name: install python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: systemctl service 
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd