- name: install python packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
  - python36
  - gcc
  - python3-devel

- name: install dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3
  args:
    chdir: /app